title: blog.masoko.net
description: My Blog and Notes
author: Hristo Jelev
logo: /static/img/avatar2.jpg
github: https://github.com/hjelev
about: blog.masoko.net

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: my-blog-notes
google_analytics: UA-131668455-1


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
permalink: /:categories/:title/
