title: blog.masoko.net
description: My Blog and Notes
author: Hristo Jelev
logo: /static/img/avatar2.jpg
github: https://github.com/hjelev
about: blog.masoko.net
theme: no-style-please
# Use the remote_theme plugin for non-supported themes
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
  - jekyll-feed # (If you were using this theme's other features)
  - jekyll-seo-tag # (If you were using this theme's other features)
baseurl: ""
url: ""

allowsearch: true

disqus_shortname: my-blog-notes
google_analytics: UA-131668455-1


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
permalink: /:categories/:title/
